# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='word',
        ),
        migrations.AddField(
            model_name='words',
            name='number_of_words',
            field=models.IntegerField(null=True),
        ),
    ]
